# Generated by Django 5.0 on 2023-12-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
    ]
